/* eslint-disable */
// Generated by Wrangler by running `wrangler types`
// Runtime types generated with workerd

declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface Env {
		DB: D1Database;
		JWT_SECRET: string;
		ENVIRONMENT: string;
		/** Comma-separated list of allowed origins for the main app CORS */
		CORS_ALLOWED_ORIGINS?: string;
		/** Comma-separated list of allowed origins for public API CORS */
		ALLOWED_PUBLIC_API_ORIGINS?: string;
		/** Midtrans server key for payment processing */
		MIDTRANS_SERVER_KEY?: string;
		/** iFortePay merchant ID */
		IFORTEPAY_MERCHANT_ID?: string;
		/** iFortePay secret unbound ID for Basic auth */
		IFORTEPAY_SECRET_UNBOUND_ID?: string;
		/** iFortePay hash key for request signatures */
		IFORTEPAY_HASH_KEY?: string;
		/** iFortePay webhook callback URL */
		IFORTEPAY_CALLBACK_URL?: string;
		/** iFortePay success redirect URL */
		IFORTEPAY_SUCCESS_REDIRECT_URL?: string;
		/** iFortePay failed redirect URL */
		IFORTEPAY_FAILED_REDIRECT_URL?: string;
	}
}
interface Env extends Cloudflare.Env {}

// Begin runtime types
/*! *****************************************************************************
Copyright (c) Cloudflare. All rights reserved.
Copyright (c) Microsoft Corporation. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0
THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.
See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
